name = "pendulum"
uuid = "948af14c-2d17-11e9-24e0-0541b265729a"
authors = ["Tejan Karmali <tejank10@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gym = "56b9baea-2481-11e9-37ae-75904354ad8c"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
