[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[AbstractTrees]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "feb8b2c99359901e295443c9d0c7e711604acf39"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.2.0"

[[Adapt]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "036ce44a518b912c43df728bfae274f8d8de9059"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "0.3.1"

[[Arpack]]
deps = ["BinaryProvider", "Libdl", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "5b046410fb617d9cf2f8bc0edd5da05a2e5a2ad4"
uuid = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
version = "0.2.3"

[[AxisAlgorithms]]
deps = ["Compat", "WoodburyMatrices"]
git-tree-sha1 = "99dabbe853e4f641ab21a676131f2cf9fb29937e"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "0.3.0"

[[AxisArrays]]
deps = ["Compat", "Dates", "IntervalSets", "IterTools", "Pkg", "Random", "RangeArrays", "Test"]
git-tree-sha1 = "2e2536e9e6f27c4f8d09d8442b61a7ae0b910c28"
uuid = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
version = "0.3.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Pkg", "SHA", "Test"]
git-tree-sha1 = "b530fbeb6f41ab5a83fbe3db1fcbe879334bcd2d"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.4.2"

[[CatIndices]]
deps = ["CustomUnitRanges", "OffsetArrays", "Test"]
git-tree-sha1 = "254cf73ea369d2e39bfd6c5eb27a2296cfaed68c"
uuid = "aafaddc9-749c-510e-ac4f-586e18779b91"
version = "0.2.0"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "0e3209ba7418aed732e5c3818076b4400ee36c08"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.4"

[[ColorVectorSpace]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "LinearAlgebra", "SpecialFunctions", "Statistics", "StatsBase", "Test"]
git-tree-sha1 = "9ccd32d161d30ca1dacc4c21e63aa63513b39a44"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.6.1"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Pkg", "Printf", "Reexport", "Test"]
git-tree-sha1 = "26f24e97782dd19d52cf97073c316897ac4d0e30"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.3"

[[CommonSubexpressions]]
deps = ["Test"]
git-tree-sha1 = "efdaf19ab11c7889334ca247ff4c9f7c322817b0"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.2.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "277d3807440d9793421354b6680911fc95d91a84"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.0.1"

[[ComputationalResources]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "89e7e7ed20af73d9f78877d2b8d1194e7b6ff13d"
uuid = "ed09eef8-17a6-5b46-8889-db040fac31e3"
version = "0.3.0"

[[Conda]]
deps = ["Compat", "JSON", "VersionParsing"]
git-tree-sha1 = "a47f9a2c7b80095e6a935536795635522fe27f5d"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.0.1"

[[CoordinateTransformations]]
deps = ["Compat", "Rotations", "StaticArrays"]
git-tree-sha1 = "47f05d0b7f4999609f92e657147df000818c1f24"
uuid = "150eb455-5306-5404-9cee-2592286d6298"
version = "0.5.0"

[[CustomUnitRanges]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "0a106457a1831555857e18ac9617279c22fc393b"
uuid = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
version = "0.2.0"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "6e72a9098f5774601c8c8d6a4511a68270594910"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.11.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffResults]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "db8acf46717b13d6c48deb7a12007c7f85a70cf7"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "0.0.3"

[[DiffRules]]
deps = ["Random", "Test"]
git-tree-sha1 = "c49ec69428ffea0c1d1bbdc63d1a70f5df5860ad"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "0.0.7"

[[Distances]]
deps = ["LinearAlgebra", "Pkg", "Printf", "Random", "Statistics", "Test"]
git-tree-sha1 = "2f38605722542f1c0a32dd2856fb529d8c226c69"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.7.3"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Distributions]]
deps = ["Distributed", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SpecialFunctions", "Statistics", "StatsBase", "StatsFuns", "Test"]
git-tree-sha1 = "c43dc10a52598ad76d61f8907b3b30f159ca146f"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.16.2"

[[FFTViews]]
deps = ["CustomUnitRanges", "FFTW", "Test"]
git-tree-sha1 = "9d7993227ca7c0fdb6b31deef193adbba11c8f4e"
uuid = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
version = "0.2.0"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Pkg", "Reexport", "Test"]
git-tree-sha1 = "29cda58afbf62f35b1a094882ad6c745a47b2eaa"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.4"

[[FileIO]]
deps = ["Pkg", "Random", "Test"]
git-tree-sha1 = "b80161b7e679a1241f9441ebfa60b62d4239cf99"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.0.1"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "31cbf24d537a217475b37274df05de09882b53f1"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.2"

[[Flux]]
deps = ["AbstractTrees", "Adapt", "Colors", "DiffRules", "ForwardDiff", "GZip", "Juno", "LinearAlgebra", "MacroTools", "NNlib", "NaNMath", "Printf", "Random", "Reexport", "Requires", "SpecialFunctions", "Statistics", "StatsBase", "Test", "ZipFile"]
git-tree-sha1 = "6c6fcfa0a7c123a8a9f84f3f846a40a847820c3d"
uuid = "587475ba-b771-5e3f-ad9e-33799f191a9c"
version = "0.6.5"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "InteractiveUtils", "LinearAlgebra", "NaNMath", "Pkg", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Test"]
git-tree-sha1 = "0dd11038da4efce9ce457b1cf47a52eaf6251bd3"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.8.5"

[[GZip]]
deps = ["Libdl", "Pkg", "Test"]
git-tree-sha1 = "ee443ef166b29282301468d8af403e1ed8f5412e"
uuid = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
version = "0.5.0"

[[Graphics]]
deps = ["Colors", "Compat", "NaNMath"]
git-tree-sha1 = "4671f2427ea4494a5d14fd485c4aa61ec1fb7cd2"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "0.3.0"

[[IdentityRanges]]
deps = ["OffsetArrays", "Pkg", "Test"]
git-tree-sha1 = "f5ca23a08397288924a7535cd898d8ccbcde5ba5"
uuid = "bbac6d45-d8f3-5730-bfe4-7a449cd117ca"
version = "0.2.0"

[[ImageAxes]]
deps = ["AxisArrays", "Colors", "FixedPointNumbers", "ImageCore", "MappedArrays", "Pkg", "Reexport", "SimpleTraits", "Test"]
git-tree-sha1 = "5735ec90843acaa67a4624611921c686cdf4efbf"
uuid = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
version = "0.5.0"

[[ImageCore]]
deps = ["ColorTypes", "Colors", "FFTW", "FixedPointNumbers", "Graphics", "MappedArrays", "OffsetArrays", "PaddedViews", "Pkg", "Random", "Statistics", "Test"]
git-tree-sha1 = "b274f3abdcc10a0885187af3b7c7b2d67b73d0fe"
uuid = "a09fc81d-aa75-5fe9-8630-4744c3626534"
version = "0.7.1"

[[ImageDistances]]
deps = ["Colors", "Distances", "LinearAlgebra", "ProgressMeter", "Test"]
git-tree-sha1 = "edcf05e5bc0ea1246e1b4d7465f0ac8bd14e7fea"
uuid = "51556ac3-7006-55f5-8cb3-34580c88182d"
version = "0.1.0"

[[ImageFiltering]]
deps = ["CatIndices", "ColorVectorSpace", "Colors", "ComputationalResources", "DataStructures", "FFTViews", "FFTW", "FixedPointNumbers", "ImageCore", "LinearAlgebra", "Logging", "MappedArrays", "OffsetArrays", "Pkg", "Random", "StaticArrays", "Statistics", "Test", "TiledIteration"]
git-tree-sha1 = "e36fac956a5d8f284254f1fc9e7624f77265d3c8"
uuid = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
version = "0.4.1"

[[ImageMagick]]
deps = ["BinaryProvider", "ColorTypes", "FileIO", "FixedPointNumbers", "ImageCore", "InteractiveUtils", "Libdl", "Pkg", "Random", "Test"]
git-tree-sha1 = "0e4cc77fb131061b3525a97fd7d483b253c3aaad"
uuid = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
version = "0.7.1"

[[ImageMetadata]]
deps = ["AxisArrays", "ColorVectorSpace", "Colors", "Dates", "FixedPointNumbers", "ImageAxes", "ImageCore", "IndirectArrays", "Pkg", "Statistics", "Test"]
git-tree-sha1 = "2cb0777d654781da75668e0a1b113b2da5a7dcb4"
uuid = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
version = "0.5.0"

[[ImageMorphology]]
deps = ["ImageCore", "Test"]
git-tree-sha1 = "e94f43b9ff76f3a3810bfdd9b3d2fbcacbc26fd0"
uuid = "787d08f9-d448-5407-9aad-5290dd7ab264"
version = "0.1.1"

[[ImageTransformations]]
deps = ["AxisAlgorithms", "ColorTypes", "ColorVectorSpace", "Colors", "CoordinateTransformations", "FixedPointNumbers", "IdentityRanges", "ImageCore", "InteractiveUtils", "Interpolations", "LinearAlgebra", "OffsetArrays", "Pkg", "StaticArrays", "Test"]
git-tree-sha1 = "bd02b0dd87fd1283bf383e0e6fab934a6b0453d4"
uuid = "02fcd773-0e25-5acc-982a-7f6622650795"
version = "0.5.0"

[[Images]]
deps = ["AxisArrays", "Base64", "ColorVectorSpace", "Colors", "FileIO", "FixedPointNumbers", "Graphics", "ImageAxes", "ImageCore", "ImageDistances", "ImageFiltering", "ImageMetadata", "ImageMorphology", "ImageTransformations", "IndirectArrays", "InteractiveUtils", "LinearAlgebra", "MappedArrays", "OffsetArrays", "Pkg", "Random", "Reexport", "Requires", "SIUnits", "SparseArrays", "StaticArrays", "Statistics", "StatsBase", "Test", "TiledIteration"]
git-tree-sha1 = "7f383ec257c2d923d227bb40870f0cf1e131f6c2"
uuid = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
version = "0.15.0"

[[IndirectArrays]]
deps = ["Compat", "Pkg", "Test"]
git-tree-sha1 = "b6e249be10a3381b2c72ac82f2d13d70067cb2bd"
uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959"
version = "0.5.0"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "Compat", "LinearAlgebra", "OffsetArrays", "Ratios", "ShowItLikeYouBuildIt", "WoodburyMatrices"]
git-tree-sha1 = "da2709d9f94b0ebd3da2c7cb92a1ce1e0d807913"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.8.0"

[[IntervalSets]]
deps = ["Compat"]
git-tree-sha1 = "d488eaaac00c8ea66423773e5a86ac81b9ac03e0"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.2.0"

[[IterTools]]
deps = ["Pkg", "SparseArrays", "Test"]
git-tree-sha1 = "ed0787e62dc46b8d8c7c3db54391d71e0da5fefd"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.0.0"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Pkg", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "fec8e4d433072731466d37ed0061b3ba7f70eeb9"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.19.0"

[[Juno]]
deps = ["Base64", "Logging", "Media", "Profile", "Test"]
git-tree-sha1 = "f2d553719755f00f602cb226689c0bcfee023a1d"
uuid = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
version = "0.5.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "c443e1c8d58a4e9f61b708ad0a88286c7042145b"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.4"

[[MappedArrays]]
deps = ["Test"]
git-tree-sha1 = "923441c5ac942b60bd3a842d5377d96646bcbf46"
uuid = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
version = "0.2.1"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Media]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "9f390271c9a43dcbe908a10b5b9632cf58cbab5b"
uuid = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"
version = "0.4.1"

[[Missings]]
deps = ["Dates", "InteractiveUtils", "SparseArrays", "Test"]
git-tree-sha1 = "196528fa1df03df435025f52f9c1ff8356f94738"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.3.0"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NNlib]]
deps = ["Libdl", "LinearAlgebra", "MacroTools", "Requires", "Test"]
git-tree-sha1 = "1375b53e79080b37705a4040c97f1ded4e332cac"
uuid = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
version = "0.4.1"

[[NaNMath]]
deps = ["Compat"]
git-tree-sha1 = "ce3b85e484a5d4c71dd5316215069311135fa9f2"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.2"

[[OffsetArrays]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "f8cd140824f74f2948ff8660bc2292e16d29c1b7"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.8.1"

[[PDMats]]
deps = ["Arpack", "LinearAlgebra", "SparseArrays", "SuiteSparse", "Test"]
git-tree-sha1 = "9e3e7a5c9b8cfdba8c01a1bcae38fe0144936fda"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.9.5"

[[PaddedViews]]
deps = ["OffsetArrays", "Test"]
git-tree-sha1 = "a6ecf172a704baa599ee1cc2c2953d129ce6aa31"
uuid = "5432bcbf-9aad-5242-b902-cca2824c8663"
version = "0.4.1"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[ProgressMeter]]
deps = ["Printf", "Random", "Test"]
git-tree-sha1 = "09e653f4b0a3c44628f0bdd0a0e58bc92e0264ef"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "0.6.0"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "7d61ca207f021be6574b365a1a077bea04935f19"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.1"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RangeArrays]]
deps = ["Compat"]
git-tree-sha1 = "d925adfd5b01cb46fde89dc9548d167b3b136f4a"
uuid = "b3c3ace0-ae52-54e7-9d0b-2c1406fd6b9d"
version = "0.3.1"

[[Ratios]]
deps = ["Compat"]
git-tree-sha1 = "fd159bead0a24e6270fd0573a340312bd4645cc2"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.3.0"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[Rmath]]
deps = ["BinaryProvider", "Libdl", "Pkg", "Random", "Statistics", "Test"]
git-tree-sha1 = "9a6c758cdf73036c3239b0afbea790def1dabff9"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.5.0"

[[Rotations]]
deps = ["LinearAlgebra", "Pkg", "Random", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "448eb7dce980439d96472e7d0c3826ad539ed099"
uuid = "6038ab10-8711-5258-84ad-4b1120ba62dc"
version = "0.8.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SIUnits]]
deps = ["Compat", "TexExtensions"]
git-tree-sha1 = "224d83b62711fe7e429454aace2c97eb2cf36031"
uuid = "b9d75638-96e3-5676-bdf0-e9c958f63a55"
version = "0.1.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShowItLikeYouBuildIt]]
git-tree-sha1 = "e562bce4b0df3ed65562ce2ec7f56cb399368daf"
uuid = "9966252f-7483-59e3-9a4c-8607a6b2a5fe"
version = "0.2.0"

[[SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools", "Pkg", "Test"]
git-tree-sha1 = "c0a542b8d5e369b179ccd296b2ca987f6da5da0a"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.8.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "d12f8917be3782f4b800ba16003b8d0d4858c2e5"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.0"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d432c79bef174a830304f8601427a4357dfdbfb7"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "723193a13e8078cec6dcd0b8fe245c8bfd81690e"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.25.0"

[[StatsFuns]]
deps = ["Pkg", "Rmath", "SpecialFunctions", "Test"]
git-tree-sha1 = "d14bb7b03defd2deaa5675646f6783089e0556f0"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "0.7.0"

[[SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TexExtensions]]
deps = ["Compat"]
git-tree-sha1 = "092ad55ed044aa5ab31ee800d4ae5bec526a8f09"
uuid = "9b435220-3ad3-5d4f-b1ea-1e7b29ae9b13"
version = "0.1.0"

[[TiledIteration]]
deps = ["OffsetArrays", "Pkg", "Test"]
git-tree-sha1 = "58f6f07d3b54a363ec283a8f5fc9fb4ecebde656"
uuid = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
version = "0.2.3"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "c9d5aa108588b978bd859554660c8a5c4f2f7669"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.2"

[[WoodburyMatrices]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "21772c33b447757ec7d3e61fcdfb9ea5c47eedcf"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.4.1"

[[ZipFile]]
deps = ["Printf", "Test"]
git-tree-sha1 = "c191e56c849b1784cacbf7cd5e52cc672f1ae2db"
uuid = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
version = "0.7.0"
