[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
OpenAIGym = "41d6fcb8-dd24-11e8-2536-c3dc023218b5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reinforce = "0376cc21-f8a9-5fcf-8891-fde1415a4fd3"
TerminalExtensions = "d3a6a179-465e-5219-bd3e-0137f7fd17c7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
